//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HUTOPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchUpload
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public string Shift { get; set; }
        public string Venue { get; set; }
        public string HUTOPSIdsFile { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<byte> IsStatusEmailSent { get; set; }
        public Nullable<System.DateTime> EmailSentOn { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<byte> Type { get; set; }
        public Nullable<byte> Result { get; set; }
        public Nullable<byte> IsRecordSendToEApp { get; set; }
    }
}
