//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HUTOPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Photograph { get; set; }
        public string SSCMarkSheet { get; set; }
        public string HSSCMarkSheet { get; set; }
        public string CNIC { get; set; }
        public string AdmitCard { get; set; }
        public Nullable<int> IsCompleted { get; set; }
    }
}
