//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HUTOPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Educational
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CurrentLevelOfEdu { get; set; }
        public string CurrentCollege { get; set; }
        public string CollegeAddress { get; set; }
        public Nullable<int> CollegeStartDate { get; set; }
        public Nullable<int> CollegeCompletionDate { get; set; }
        public string HSSCPercentage { get; set; }
        public string BoardOfEdu { get; set; }
        public string GroupOfStudy { get; set; }
        public string SchoolName { get; set; }
        public string SchoolAddress { get; set; }
        public string SSCPercentage { get; set; }
        public string UniversityName { get; set; }
        public string IntendedProgram { get; set; }
    }
}
