//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HUTOPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Educational
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CurrentLevelOfEdu { get; set; }
        public string HSSCSchoolName { get; set; }
        public string HSSCSchoolAddress { get; set; }
        public Nullable<int> HSSCStartDate { get; set; }
        public Nullable<int> HSSCCompletionDate { get; set; }
        public string HSSCPercentage { get; set; }
        public string HSSCBoardId { get; set; }
        public string HSSCBoardName { get; set; }
        public string HSSCGroupId { get; set; }
        public string HSSCGroupName { get; set; }
        public string SSCSchoolName { get; set; }
        public string SSCSchoolAddress { get; set; }
        public string SSCPercentage { get; set; }
        public string UniversityName { get; set; }
        public string IntendedProgram { get; set; }
        public Nullable<int> IsCompleted { get; set; }
        public string HUSchoolName { get; set; }
    }
}
