//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HUTOPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationalSubject
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ObtainMarks { get; set; }
        public Nullable<int> TotalMarks { get; set; }
        public string Grade { get; set; }
        public int EducationalId { get; set; }
    }
}
