//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HU.TOP.WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationalInformation
    {
        public int Id { get; set; }
        public string HUTopId { get; set; }
        public string CurrentLevelOfEdu { get; set; }
        public string CurrentCollege { get; set; }
        public string CollegeAddress { get; set; }
        public string BoardOfEdu { get; set; }
        public string GroupOfStudy { get; set; }
        public string OptionalSubjects { get; set; }
        public string SchoolName { get; set; }
        public string SchoolAddress { get; set; }
        public Nullable<decimal> SSCPercentage { get; set; }
    }
}
