//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HUTOPS.EAppDBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalInformation
    {
        public long ID { get; set; }
        public string Appid { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string HusbandName { get; set; }
        public string FatherFirstName { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string CountryAdd { get; set; }
        public string PhoneNo { get; set; }
        public string Tellus { get; set; }
        public string CurrentAddress { get; set; }
        public string PostalAddress { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Provience { get; set; }
        public string Postal { get; set; }
        public string Email { get; set; }
        public string AlterEmail { get; set; }
        public string Password { get; set; }
        public string CPassword { get; set; }
        public Nullable<System.DateTime> Savedate { get; set; }
        public Nullable<System.DateTime> Updatedate { get; set; }
        public Nullable<int> AppStatus { get; set; }
        public string StudentStatus { get; set; }
        public Nullable<int> TempID { get; set; }
        public string School { get; set; }
        public string SchoolName { get; set; }
        public string HereYou { get; set; }
        public string HereOther { get; set; }
        public string NewEmail { get; set; }
        public string Discount { get; set; }
        public string DiscountFee { get; set; }
        public string Yourinterests { get; set; }
        public string YourinterestsOther { get; set; }
        public string Currentqualification { get; set; }
        public string AlternateMobile { get; set; }
        public string Alternatelandline { get; set; }
        public string Cityother { get; set; }
        public string OtherCurrentqualification { get; set; }
        public string Userid { get; set; }
        public string Permanent_addres { get; set; }
        public string Permanent_country { get; set; }
        public string Permanent_city { get; set; }
        public string Permanent_cityother { get; set; }
        public string Permanent_provience { get; set; }
        public string Permanent_provienceother { get; set; }
        public string Permanent_postal { get; set; }
        public string Postal_addres { get; set; }
        public string Postal_country { get; set; }
        public string Postal_city { get; set; }
        public string Postal_cityother { get; set; }
        public string Postal_provience { get; set; }
        public string Postal_provienceother { get; set; }
        public string Postal_postal { get; set; }
        public string chk { get; set; }
        public string Modeofstudy { get; set; }
        public string BoardofEducation { get; set; }
        public string Intendedprogram { get; set; }
        public string TestDate { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public bool Retake { get; set; }
        public string AppliedBefore { get; set; }
        public Nullable<int> AppliedBeforeMonth { get; set; }
        public Nullable<int> AppliedBeforeYear { get; set; }
        public string CurrentHighSchoolOther { get; set; }
        public Nullable<int> CurrentHighSchoolCode_old { get; set; }
        public string BoardofEducationOther { get; set; }
        public string CurrentHighSchoolCode { get; set; }
        public string HUTopsCandidate { get; set; }
        public string HuTopsId { get; set; }
        public string FatherMiddleName { get; set; }
        public string FatherLastName { get; set; }
        public string FatherName { get; set; }
        public string WhatsAppNumber { get; set; }
    }
}
