//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HUTOPSBatchProcessConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestDate
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Value { get; set; }
        public string Text { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<byte> Visibility { get; set; }
        public Nullable<System.DateTime> DeadlineDate { get; set; }
        public string AdmissionSession { get; set; }
    }
}
